fix projectTile and projectCard. Improve deployment failure process

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,5 +24,7 @@ jobs:
             nvm install
             nvm use
             npm install
-            npm run build
+            echo "Starting build..."
+            npm run build || { echo "Build failed! Aborting deployment."; exit 1; }
+            echo "Build succeeded. Reloading..."
             pm2 reload staging --update-env
